### ISSUE TITLE
Redmine. 500 error. Uninitialized constant ViewCustomize::INSERTION_POSITION_HTML_HEAD 

### ISSUE THREAD

**Issue by sytkosa** [onozaty/redmine-view-customize#28]
Error
uninitialized constant ViewCustomize::INSERTION_POSITION_HTML_HEAD 

Error log
        /var/www/redmine/plugins/redmine-view-customize/lib/view_customize/view_hook.rb:13:in `view_layouts_base_html_head'

![image](https://user-images.githubusercontent.com/10109949/46322214-54c7c000-c5f0-11e8-8d56-37d6fbb4b9e8.png)

**Comment by onozaty** [comment]
Hi @sytkosa 

Please change directory name from `redmine-view-customize` to `view_customize`

**Comment by udanieli** [comment]
I have the same issue even with the correct directory name.

```
I, [2019-09-14T08:33:52.463064 #4696]  INFO -- : Started GET "/" for XX.XX.XX.XX at 2019-09-14 08:33:52 +0200
I, [2019-09-14T08:33:52.540195 #4696]  INFO -- : Processing by WelcomeController#index as HTML
I, [2019-09-14T08:33:52.608690 #4696]  INFO -- :   Current user: anonymous
I, [2019-09-14T08:33:52.615540 #4696]  INFO -- : Redirected to https://redmine.mydomain.it/login?back_url=https%3A%2F%2Fredmine.mydomain.it%2F
I, [2019-09-14T08:33:52.615691 #4696]  INFO -- : Filter chain halted as :check_if_login_required rendered or redirected
I, [2019-09-14T08:33:52.615865 #4696]  INFO -- : Completed 302 Found in 75ms (ActiveRecord: 11.1ms)
I, [2019-09-14T08:33:52.737529 #4696]  INFO -- : Started GET "/login?back_url=https%3A%2F%2Fredmine.mydomain.it%2F" for XX.XX.XX.XX at 2019-09-14 08:33:52 +0200
I, [2019-09-14T08:33:52.747844 #4696]  INFO -- : Processing by AccountController#login as HTML
I, [2019-09-14T08:33:52.747948 #4696]  INFO -- :   Parameters: {"back_url"=>"https://redmine.mydomain.it/"}
I, [2019-09-14T08:33:52.750931 #4696]  INFO -- :   Current user: anonymous
I, [2019-09-14T08:33:52.761482 #4696]  INFO -- :   Rendered account/login.html.erb within layouts/base (4.9ms)
I, [2019-09-14T08:33:53.136266 #4696]  INFO -- : Completed 500 Internal Server Error in 388ms (ActiveRecord: 7.4ms)
F, [2019-09-14T08:33:53.137370 #4696] FATAL -- : 
ActionView::Template::Error (uninitialized constant ViewCustomize::INSERTION_POSITION_HTML_HEAD):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: <!-- page specific tags -->
    18: <%= yield :header_tags -%>
    19: </head>
  lib/plugins/view_customize/lib/view_customize/view_hook.rb:13:in `view_layouts_base_html_head'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__2413874930609552299_47275760089160'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
Redmine version: 3.3.1-4+deb9u2
Ruby: 2.3.3
Rails 4.2.7.1-1
Env production
Database PostgreSQL

**Comment by onozaty** [comment]
Hi @udanieli 

What is the version of the view customization plugin?

**Comment by udanieli** [comment]
Hi @onozaty, thank you for the response. I have tested the last version [v2.4.0](https://github.com/onozaty/redmine-view-customize/tree/v2.4.0)

**Comment by onozaty** [comment]
Hi @udanieli 

The installation location of the plug-in seems strange.
Is it installed in `redmine/lib/plugins`?
The correct one is `redmine/plugins`.

**Comment by udanieli** [comment]
You are right. I had put it along with "vendor" plugins (e.g. `gravatar`, `acts_as_watchable`) in `lib/plugins`, sorry for this mistake.

Your plugin is so nice, thank you very much!

**Comment by onozaty** [comment]
It was good to solve!
Thanks.
