### ISSUE TITLE
ActionView::Template::Error (Mysql2::Error: Table 'bitnami_redmine.view_customizes' doesn't exist

### ISSUE THREAD

**Issue by sakura3ing** [onozaty/redmine-view-customize#7]
I got Template::Error on bitnami-redmine-3.2.2-0-linux-x64

```

ActionView::Template::Error (Mysql2::Error: Table 'bitnami_redmine.view_customizes' doesn't exist: SELECT `view_customizes`.* FROM `view_customizes`):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: <!-- page specific tags -->
    18: <%= yield :header_tags -%>
    19: </head>
  plugins/view_customize/lib/view_customize/view_layouts_base_html_head_hook.rb:17:in `match_customize'
  plugins/view_customize/lib/view_customize/view_layouts_base_html_head_hook.rb:5:in `view_layouts_base_html_head'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__1559771949650330764_47202440892840'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by archonwang** [comment]
do you exec commands like these

> bundle exec rake redmine:plugins:migrate RAILS_ENV=production

**Comment by sakura3ing** [comment]
I missed param
I execute "redmine:plugins:migrate"  instead of "db:migrate" and it worked.
